version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
    image: todo-app:development
    volumes:
      - .:/app
    ports:
      - "3400:3200"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:11.7
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PG_USER: $DEV_USERNAME
      PG_DB: $DEV_DATABASE
      PG_PASSWORD: $DEV_PASSWORD

volumes:
  pg-dev-data:
