version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
    image: todo-app:development
    volumes:
      - .:/app
    ports:
      - "3400:3300"
    environment:
      DEV_USERNAME: ${{ secrets.PG_USERNAME }}
      DEV_DATABASE: ${{ secrets.PG_DATABASE }}
      DEV_PASSWORD: ${{ secrets.PG_PASSWORD }}
    depends_on:
      - db

  db:
    image: postgres:11.7
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    environment:
      PG_USER: ${{ secrets.PG_USERNAME }}
      PG_DB: ${{ secrets.PG_DATABASE }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}

volumes:
  pg-dev-data:
