name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies for linting
        run: npm install eslint --save-dev

      - name: Lint code
        run: npx eslint .

  build-docker-image:
    runs-on: ubuntu-latest
    needs: validate-code
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker-compose -f docker-compose.yml -f docker-compose-prod.yml build

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker-compose -f docker-compose.yml -f docker-compose-prod.yml push

  run-tests:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:11.7
        # Provide the password for postgres
        env:
          POSTGRES_USER: ${{ secrets.PG_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_DATABASE }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: cd todo-app && npm ci

      - name: Run unit tests
        run: cd todo-app && npm test

      - name: Run the app
        id: run-app
        run: |
          cd todo-app
          npm install
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate
          PORT=3000 npm start &
          sleep 5

      - name: Run integration tests
        run: |
          cd todo-app
          npm install cypress cypress-json-results
          npx cypress run --env STUDENT_SUBMISSION_URL="http://localhost:3000/"

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#pipeline'
          message: |
              Build and Deploy Status: ${{ job.status }}
              Job Name: ${{ github.job }}
              Workflow: ${{ github.workflow }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: ssh username@server 'docker-compose -f path/to/docker-compose-prod.yml up -d'

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#pipeline'
          message: |
              Build and Deploy Status: ${{ job.status }}
              Job Name: ${{ github.job }}
              Workflow: ${{ github.workflow }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

  error-handling:
    runs-on: ubuntu-latest
    needs: deploy-to-server
    if: failure()
    steps:
      - name: Slack Notification on Failure
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#pipeline'
          message: |
              Build and Deploy Status: ${{ job.status }}
              Job Name: ${{ github.job }}
              Workflow: ${{ github.workflow }}
              Error: ${{ failure() }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
